from issuetracker.views.tasks import TaskListView
from issuetracker.views.tasks import TaskCreateView
from issuetracker.views.tasks import TaskDeleteView
from issuetracker.views.tasks import TaskUpdateView
from issuetracker.views.tasks import TaskDetailView
from issuetracker.views.projects import ProjectListView
from issuetracker.views.projects import ProjectDetailView
from issuetracker.views.projects import ProjectCreateView
from issuetracker.views.projects import ProjectUpdateView
from issuetracker.views.projects import ProjectDeleteView
from issuetracker.views.projects import TaskCreateInProjectView