# Generated by Django 6.0.6 on 2026-06-18 09:57

from django.db import migrations
from datetime import date

def fill_project(apps, schema_editor):
    Project = apps.get_model('issuetracker', 'Project')
    Task = apps.get_model('issuetracker', 'Task')

    project = Project.objects.create(
        title='Проект по умолчанию',
        description='Создан миграцией',
        begin_date=date.today()
    )

    Task.objects.all().update(project=project)


class Migration(migrations.Migration):

    dependencies = [
        ('issuetracker', '0003_project_task_project'),
    ]

    operations = [
        migrations.RunPython(fill_project)
    ]
