# Generated by Django 6.0.6 on 2026-06-18 10:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issuetracker', '0004_auto_20260618_0957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='issuetracker.project', verbose_name='Проект'),
        ),
    ]
