# Generated by Django 6.0.6 on 2026-06-29 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issuetracker', '0006_project_users'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'permissions': [('manage_users', 'Can manage project users')]},
        ),
    ]
